version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 15
  labels:
  - maintenance
  - dependencies
  ignore:
  - dependency-name: Django
    versions:
    - ">= 3.0"
  - dependency-name: urllib3
    versions:
    - ">= 0"
  cooldown:
    default-days: 7
