sudo: false
language: python
python:
  - "2.7"
before_script:
  - flake8 news
  - mysql -e 'create database basket;'
  - python manage.py migrate --noinput
script: coverage run manage.py test news
before_install:
  - git submodule update --init --recursive
install:
  - pip install -r requirements/compiled.txt -r requirements/dev.txt
after_success:
  # Report coverage results to coveralls.io
  - pip install coveralls
  - coveralls
notifications:
  irc:
    channels:
      - "irc.mozilla.org#basket"
    on_success: change
    on_failure: always
    use_notice: true
