sudo: false
language: python
python:
  - "2.7"
before_script:
  - flake8 news
  - mysql -e 'create database basket;'
  - python manage.py migrate --noinput
script: py.test --cov news
install:
  - bin/peep.py install -r requirements/default.txt -r requirements/compiled.txt -r requirements/dev.txt
  - pip install coveralls
after_success:
  # Report coverage results to coveralls.io
  - coveralls
notifications:
  irc:
    channels:
      - "irc.mozilla.org#basket"
    on_success: change
    on_failure: always
    use_notice: true
