version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Setup
          command: |
            echo "export GIT_COMMIT=${CIRCLE_SHA1}" >> $BASH_ENV
            # required for docker-compose to run
            touch .env
            mkdir -p $TEST_RESULTS
      - run:
          name: Build Image
          command: |
            bin/dc.sh build --pull web builder
      - run:
          name: Run Tests
          command: |
            bin/dc.sh run --name test-run test-image
      - run: docker cp test-run:/app/test-results $TEST_RESULTS
      - store_test_results:
          path: /tmp/test-results
